version: '2'

services:
  app:
    build:
      context: ./docker/app
    volumes:
     - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: postgres:9
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_db